---
- name: set up aWorkstation as root
  hosts: all
  become: yes
  tasks:
    # sublime
    - name: add sublime's key
      apt_key:
        url: "https://download.sublimetext.com/sublimehq-pub.gpg"
        state: present
    - name: add sublime's stable repo
      apt_repository:
        filename: 'sublime-stable'
        repo: deb https://download.sublimetext.com/ apt/stable/
    - name: add sublime's dev repo
      apt_repository:
        filename: 'sublime-dev'
        repo: deb https://download.sublimetext.com/ apt/dev/

    # apt
    - name: copy sources.list file to apt
      copy:
        src: /vagrant/sources.list
        dest: /etc/apt
    - name: upgrade all the things
      apt:
        update_cache: yes
        upgrade: dist
    - name: install all the things
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - sublime-text
        - virtualbox
        - vagrant
        - curl
        - git
        - zsh
        - openvpn
        - python-pip
        - tmuxinator
        - awscli
        - gnupg-agent
        - network-manager-openvpn

    # pip
    - name: install boto boto3 + botocore
      pip:
        name: boto,boto3,botocore

#    - name: checkoutrepo
#    - name: checkout personal Identity Repo
#    - name: set wallpaper withlogo
#    - name: checkout customer repos from list
#    - name: install theme

# le env, merde!
#    - name: setup API / aws config
#    - name: include ~/Documents/Dev-Ops-Toolset/ssh.config.example
#    - name: source Include ~/Documents/Dev-Ops-Toolset/.zshrc
#    - name: get client project (sublime project + theme)
#    - name: install sublime theme- boxy and addons (all)
#    - name: install sublime plugin gitgutter via package control <- this is it