---
- name: set up aWorkstation at user-level
  hosts: all
  tasks:
    - name: install oh-my-zsh
      command: "/vagrant/oh-my-zsh-install.sh {{ ansible_user }}"
    - name: sublime text package control thing
      copy:
        src: '/vagrant/Package Control.sublime-package'
        dest: '/home/{{ ansible_user }}/.config/sublime-text-3/Installed Packages/'
