---
- name: set up aWorkstation as root
  hosts: all
  become: yes
  roles:
  #   - apt-proxy-client
     - ypid.wine
     - sublime-text
     - workstation-packages
     - workstation-python
  vars_files:
    - vars.yml

#    - name: checkoutrepo
#    - name: checkout personal Identity Repo
#    - name: set wallpaper withlogo
#    - name: checkout customer repos from list
#    - name: install theme

# le env, merde!
#    - name: setup API / aws config
#    - name: include ~/Documents/Dev-Ops-Toolset/ssh.config.example
#    - name: source Include ~/Documents/Dev-Ops-Toolset/.zshrc
#    - name: get client project (sublime project + theme)
#    - name: install sublime theme- boxy and addons (all)
#    - name: install sublime plugin gitgutter via package control <- this is it
